CREATE TABLE user (
    id INT PRIMARY KEY,
    auth_id INT PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
    last_name VARCHAR(64) NOT NULL,
    second_last_name VARCHAR(64) NOT NULL,
    role_id VARCHAR(124) NOT NULL,

    created_at TIMESTAMP NOT NULL DEFAULT UTC_TIMESTAMP(),
    updated_at TIMESTAMP NOT NULL DEFAULT UTC_TIMESTAMP() ON UPDATE,
    status_id TINYINT(2) NOT NULL DEFAULT 1;
);

CREATE TABLE auth (
    id INT PRIMARY KEY AUTO_INCREMENT,
    password VARCHAR(128) NOT NULL,

    created_at TIMESTAMP NOT NULL DEFAULT UTC_TIMESTAMP(),
    updated_at TIMESTAMP NOT NULL DEFAULT UTC_TIMESTAMP() ON UPDATE,
    status_id TINYINT(2) NOT NULL DEFAULT 1;
);

CREATE TABLE role (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(64) NOT NULL,

    created_at TIMESTAMP NOT NULL DEFAULT UTC_TIMESTAMP(),
    updated_at TIMESTAMP NOT NULL DEFAULT UTC_TIMESTAMP() ON UPDATE,
    status_id TINYINT(2) NOT NULL DEFAULT 1;
);

CREATE TABLE page (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(64) NOT NULL,

    created_at TIMESTAMP NOT NULL DEFAULT UTC_TIMESTAMP(),
    updated_at TIMESTAMP NOT NULL DEFAULT UTC_TIMESTAMP() ON UPDATE,
    status_id TINYINT(2) NOT NULL DEFAULT 1;
);

CREATE TABLE module (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(64) NOT NULL,
    page_id INT NOT NULL,

    created_at TIMESTAMP NOT NULL DEFAULT UTC_TIMESTAMP(),
    updated_at TIMESTAMP NOT NULL DEFAULT UTC_TIMESTAMP() ON UPDATE,
    status_id TINYINT(2) NOT NULL DEFAULT 1;
);

CREATE TABLE role_module (
    id INT PRIMARY KEY AUTO_INCREMENT,
    role_id INT,
    module_id INT,

    created_at TIMESTAMP NOT NULL DEFAULT UTC_TIMESTAMP(),
    updated_at TIMESTAMP NOT NULL DEFAULT UTC_TIMESTAMP() ON UPDATE,
    status_id TINYINT(2) NOT NULL DEFAULT 1;
);

CREATE TABLE movie (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(64),
    description varchar(3024),

    created_at TIMESTAMP NOT NULL DEFAULT UTC_TIMESTAMP(),
    updated_at TIMESTAMP NOT NULL DEFAULT UTC_TIMESTAMP() ON UPDATE,
    status_id TINYINT(2) NOT NULL DEFAULT 1;
);

CREATE TABLE room (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(64),
    available TINYINT(2) NOT NULL,

    created_at TIMESTAMP NOT NULL DEFAULT UTC_TIMESTAMP(),
    updated_at TIMESTAMP NOT NULL DEFAULT UTC_TIMESTAMP() ON UPDATE,
    status_id TINYINT(2) NOT NULL DEFAULT 1;
);

CREATE TABLE seat_of_room (
    id INT PRIMARY KEY AUTO_INCREMENT,
    room_id INT,
    name VARCHAR(64),
    available TINYINT(2) NOT NULL,

    created_at TIMESTAMP NOT NULL DEFAULT UTC_TIMESTAMP(),
    updated_at TIMESTAMP NOT NULL DEFAULT UTC_TIMESTAMP() ON UPDATE,
    status_id TINYINT(2) NOT NULL DEFAULT 1;
);

CREATE TABLE cinema (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name varchar(256),
    location_id INT NOT NULL,

    created_at TIMESTAMP NOT NULL DEFAULT UTC_TIMESTAMP(),
    updated_at TIMESTAMP NOT NULL DEFAULT UTC_TIMESTAMP() ON UPDATE,
    status_id TINYINT(2) NOT NULL DEFAULT 1;
);

CREATE TABLE location (
    id INT PRIMARY KEY AUTO_INCREMENT,
    description varchar(1024),
    lat VARCHAR(128),
    long VARCHAR(128),

    created_at TIMESTAMP NOT NULL DEFAULT UTC_TIMESTAMP(),
    updated_at TIMESTAMP NOT NULL DEFAULT UTC_TIMESTAMP() ON UPDATE,
    status_id TINYINT(2) NOT NULL DEFAULT 1;
);

CREATE TABLE function (
    id INT PRIMARY KEY AUTO_INCREMENT,
    cinema_id INT,
    start_date TIMESTAMP NOT NULL,
    function_status_id INT,

    created_at TIMESTAMP NOT NULL DEFAULT UTC_TIMESTAMP(),
    updated_at TIMESTAMP NOT NULL DEFAULT UTC_TIMESTAMP() ON UPDATE,
    status_id TINYINT(2) NOT NULL DEFAULT 1;
);

 CREATE TABLE function_status (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name varchar(256),
    
    created_at TIMESTAMP NOT NULL DEFAULT UTC_TIMESTAMP(),
    updated_at TIMESTAMP NOT NULL DEFAULT UTC_TIMESTAMP() ON UPDATE,
    status_id TINYINT(2) NOT NULL DEFAULT 1;
);

CREATE TABLE seat_of_function (
    id INT PRIMARY KEY AUTO_INCREMENT,
    seat_of_room_id INT,
    name varchar(256),
    
    created_at TIMESTAMP NOT NULL DEFAULT UTC_TIMESTAMP(),
    updated_at TIMESTAMP NOT NULL DEFAULT UTC_TIMESTAMP() ON UPDATE,
    status_id TINYINT(2) NOT NULL DEFAULT 1;
);



CREATE TABLE order ()

